[package]
name = "conclave-types"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "conclave types and traits"
repository = "https://github.com/piot/conclave-types-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
